// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlc

import (
	"context"
)

const deleteAPIKeyByIDAndAccount = `-- name: DeleteAPIKeyByIDAndAccount :execrows
DELETE FROM api_keys
WHERE api_key_id = ? AND account_id = ?
`

type DeleteAPIKeyByIDAndAccountParams struct {
	ApiKeyID  string `json:"api_key_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) DeleteAPIKeyByIDAndAccount(ctx context.Context, arg DeleteAPIKeyByIDAndAccountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAPIKeyByIDAndAccount, arg.ApiKeyID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAPIKeyByAccountAndNameKey = `-- name: GetAPIKeyByAccountAndNameKey :one
SELECT
    api_key_id,
    account_id,
    name,
    name_key,
    key_hash,
    key_masked,
    created_at_unix_ms,
    updated_at_unix_ms
FROM api_keys
WHERE account_id = ? AND name_key = ?
LIMIT 1
`

type GetAPIKeyByAccountAndNameKeyParams struct {
	AccountID string `json:"account_id"`
	NameKey   string `json:"name_key"`
}

func (q *Queries) GetAPIKeyByAccountAndNameKey(ctx context.Context, arg GetAPIKeyByAccountAndNameKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByAccountAndNameKey, arg.AccountID, arg.NameKey)
	var i ApiKey
	err := row.Scan(
		&i.ApiKeyID,
		&i.AccountID,
		&i.Name,
		&i.NameKey,
		&i.KeyHash,
		&i.KeyMasked,
		&i.CreatedAtUnixMs,
		&i.UpdatedAtUnixMs,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT
    api_key_id,
    account_id,
    name,
    name_key,
    key_hash,
    key_masked,
    created_at_unix_ms,
    updated_at_unix_ms
FROM api_keys
WHERE key_hash = ?
LIMIT 1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ApiKeyID,
		&i.AccountID,
		&i.Name,
		&i.NameKey,
		&i.KeyHash,
		&i.KeyMasked,
		&i.CreatedAtUnixMs,
		&i.UpdatedAtUnixMs,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT
    api_key_id,
    account_id,
    name,
    name_key,
    key_hash,
    key_masked,
    created_at_unix_ms,
    updated_at_unix_ms
FROM api_keys
WHERE api_key_id = ?
LIMIT 1
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, apiKeyID string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByID, apiKeyID)
	var i ApiKey
	err := row.Scan(
		&i.ApiKeyID,
		&i.AccountID,
		&i.Name,
		&i.NameKey,
		&i.KeyHash,
		&i.KeyMasked,
		&i.CreatedAtUnixMs,
		&i.UpdatedAtUnixMs,
	)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :exec
INSERT INTO api_keys (
    api_key_id,
    account_id,
    name,
    name_key,
    key_hash,
    key_masked,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAPIKeyParams struct {
	ApiKeyID        string `json:"api_key_id"`
	AccountID       string `json:"account_id"`
	Name            string `json:"name"`
	NameKey         string `json:"name_key"`
	KeyHash         string `json:"key_hash"`
	KeyMasked       string `json:"key_masked"`
	CreatedAtUnixMs int64  `json:"created_at_unix_ms"`
	UpdatedAtUnixMs int64  `json:"updated_at_unix_ms"`
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertAPIKey,
		arg.ApiKeyID,
		arg.AccountID,
		arg.Name,
		arg.NameKey,
		arg.KeyHash,
		arg.KeyMasked,
		arg.CreatedAtUnixMs,
		arg.UpdatedAtUnixMs,
	)
	return err
}

const listAPIKeysByAccount = `-- name: ListAPIKeysByAccount :many
SELECT
    api_key_id,
    account_id,
    name,
    name_key,
    key_hash,
    key_masked,
    created_at_unix_ms,
    updated_at_unix_ms
FROM api_keys
WHERE account_id = ?
ORDER BY created_at_unix_ms ASC, api_key_id ASC
`

func (q *Queries) ListAPIKeysByAccount(ctx context.Context, accountID string) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ApiKeyID,
			&i.AccountID,
			&i.Name,
			&i.NameKey,
			&i.KeyHash,
			&i.KeyMasked,
			&i.CreatedAtUnixMs,
			&i.UpdatedAtUnixMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
