// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard_auth.sql

package sqlc

import (
	"context"
)

const deleteDashboardCredential = `-- name: DeleteDashboardCredential :execrows
DELETE FROM dashboard_credentials
WHERE singleton_id = 1
`

func (q *Queries) DeleteDashboardCredential(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDashboardCredential)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDashboardCredential = `-- name: GetDashboardCredential :one
SELECT
    singleton_id,
    username,
    password_hash,
    hash_algo,
    created_at_unix_ms,
    updated_at_unix_ms
FROM dashboard_credentials
WHERE singleton_id = 1
LIMIT 1
`

func (q *Queries) GetDashboardCredential(ctx context.Context) (DashboardCredential, error) {
	row := q.db.QueryRowContext(ctx, getDashboardCredential)
	var i DashboardCredential
	err := row.Scan(
		&i.SingletonID,
		&i.Username,
		&i.PasswordHash,
		&i.HashAlgo,
		&i.CreatedAtUnixMs,
		&i.UpdatedAtUnixMs,
	)
	return i, err
}

const insertDashboardCredential = `-- name: InsertDashboardCredential :exec
INSERT INTO dashboard_credentials (
    singleton_id,
    username,
    password_hash,
    hash_algo,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertDashboardCredentialParams struct {
	SingletonID     int64  `json:"singleton_id"`
	Username        string `json:"username"`
	PasswordHash    string `json:"password_hash"`
	HashAlgo        string `json:"hash_algo"`
	CreatedAtUnixMs int64  `json:"created_at_unix_ms"`
	UpdatedAtUnixMs int64  `json:"updated_at_unix_ms"`
}

func (q *Queries) InsertDashboardCredential(ctx context.Context, arg InsertDashboardCredentialParams) error {
	_, err := q.db.ExecContext(ctx, insertDashboardCredential,
		arg.SingletonID,
		arg.Username,
		arg.PasswordHash,
		arg.HashAlgo,
		arg.CreatedAtUnixMs,
		arg.UpdatedAtUnixMs,
	)
	return err
}
