// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: maintenance.sql

package sqlc

import (
	"context"
)

const markNonTerminalTasksFailedOnStartup = `-- name: MarkNonTerminalTasksFailedOnStartup :execrows
UPDATE tasks
SET status = 'failed',
    error_code = 'console_restarted',
    error_message = 'task interrupted by console restart',
    updated_at_unix_ms = ?,
    completed_at_unix_ms = ?,
    expires_at_unix_ms = ?
WHERE status IN ('queued', 'dispatched', 'running')
`

type MarkNonTerminalTasksFailedOnStartupParams struct {
	UpdatedAtUnixMs   int64 `json:"updated_at_unix_ms"`
	CompletedAtUnixMs int64 `json:"completed_at_unix_ms"`
	ExpiresAtUnixMs   int64 `json:"expires_at_unix_ms"`
}

func (q *Queries) MarkNonTerminalTasksFailedOnStartup(ctx context.Context, arg MarkNonTerminalTasksFailedOnStartupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markNonTerminalTasksFailedOnStartup, arg.UpdatedAtUnixMs, arg.CompletedAtUnixMs, arg.ExpiresAtUnixMs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
