// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: proxy_routes.sql

package sqlc

import (
	"context"
)

const deleteExpiredProxyRoutes = `-- name: DeleteExpiredProxyRoutes :execrows
DELETE FROM proxy_routes
WHERE expires_at_unix_ms <= ?
`

func (q *Queries) DeleteExpiredProxyRoutes(ctx context.Context, expiresAtUnixMs int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredProxyRoutes, expiresAtUnixMs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProxyRouteByKeyAndOwner = `-- name: DeleteProxyRouteByKeyAndOwner :execrows
DELETE FROM proxy_routes
WHERE route_key = ? AND owner_id = ?
`

type DeleteProxyRouteByKeyAndOwnerParams struct {
	RouteKey string `json:"route_key"`
	OwnerID  string `json:"owner_id"`
}

func (q *Queries) DeleteProxyRouteByKeyAndOwner(ctx context.Context, arg DeleteProxyRouteByKeyAndOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProxyRouteByKeyAndOwner, arg.RouteKey, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertProxyRoute = `-- name: InsertProxyRoute :execrows
INSERT INTO proxy_routes (
    route_key,
    owner_id,
    session_id,
    scoped_session_id,
    worker_id,
    port,
    created_at_unix_ms,
    expires_at_unix_ms
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(route_key) DO NOTHING
`

type InsertProxyRouteParams struct {
	RouteKey        string `json:"route_key"`
	OwnerID         string `json:"owner_id"`
	SessionID       string `json:"session_id"`
	ScopedSessionID string `json:"scoped_session_id"`
	WorkerID        string `json:"worker_id"`
	Port            int64  `json:"port"`
	CreatedAtUnixMs int64  `json:"created_at_unix_ms"`
	ExpiresAtUnixMs int64  `json:"expires_at_unix_ms"`
}

func (q *Queries) InsertProxyRoute(ctx context.Context, arg InsertProxyRouteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertProxyRoute,
		arg.RouteKey,
		arg.OwnerID,
		arg.SessionID,
		arg.ScopedSessionID,
		arg.WorkerID,
		arg.Port,
		arg.CreatedAtUnixMs,
		arg.ExpiresAtUnixMs,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listActiveProxyRoutes = `-- name: ListActiveProxyRoutes :many
SELECT
    route_key,
    owner_id,
    session_id,
    scoped_session_id,
    worker_id,
    port,
    created_at_unix_ms,
    expires_at_unix_ms
FROM proxy_routes
WHERE expires_at_unix_ms > ?
ORDER BY created_at_unix_ms ASC, route_key ASC
`

func (q *Queries) ListActiveProxyRoutes(ctx context.Context, expiresAtUnixMs int64) ([]ProxyRoute, error) {
	rows, err := q.db.QueryContext(ctx, listActiveProxyRoutes, expiresAtUnixMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProxyRoute
	for rows.Next() {
		var i ProxyRoute
		if err := rows.Scan(
			&i.RouteKey,
			&i.OwnerID,
			&i.SessionID,
			&i.ScopedSessionID,
			&i.WorkerID,
			&i.Port,
			&i.CreatedAtUnixMs,
			&i.ExpiresAtUnixMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
