// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: terminal_session_routes.sql

package sqlc

import (
	"context"
)

const deleteExpiredTerminalSessionRoutes = `-- name: DeleteExpiredTerminalSessionRoutes :execrows
DELETE FROM terminal_session_routes
WHERE lease_expires_unix_ms <= ?
`

func (q *Queries) DeleteExpiredTerminalSessionRoutes(ctx context.Context, leaseExpiresUnixMs int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredTerminalSessionRoutes, leaseExpiresUnixMs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTerminalSessionRouteBySessionAndNode = `-- name: DeleteTerminalSessionRouteBySessionAndNode :execrows
DELETE FROM terminal_session_routes
WHERE scoped_session_id = ? AND node_id = ?
`

type DeleteTerminalSessionRouteBySessionAndNodeParams struct {
	ScopedSessionID string `json:"scoped_session_id"`
	NodeID          string `json:"node_id"`
}

func (q *Queries) DeleteTerminalSessionRouteBySessionAndNode(ctx context.Context, arg DeleteTerminalSessionRouteBySessionAndNodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTerminalSessionRouteBySessionAndNode, arg.ScopedSessionID, arg.NodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTerminalSessionRoutesByNode = `-- name: DeleteTerminalSessionRoutesByNode :execrows
DELETE FROM terminal_session_routes
WHERE node_id = ?
`

func (q *Queries) DeleteTerminalSessionRoutesByNode(ctx context.Context, nodeID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTerminalSessionRoutesByNode, nodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTerminalSessionRouteBySession = `-- name: GetTerminalSessionRouteBySession :one
SELECT
    scoped_session_id,
    node_id,
    lease_expires_unix_ms,
    last_used_unix_ms,
    created_at_unix_ms,
    updated_at_unix_ms
FROM terminal_session_routes
WHERE scoped_session_id = ?
LIMIT 1
`

func (q *Queries) GetTerminalSessionRouteBySession(ctx context.Context, scopedSessionID string) (TerminalSessionRoute, error) {
	row := q.db.QueryRowContext(ctx, getTerminalSessionRouteBySession, scopedSessionID)
	var i TerminalSessionRoute
	err := row.Scan(
		&i.ScopedSessionID,
		&i.NodeID,
		&i.LeaseExpiresUnixMs,
		&i.LastUsedUnixMs,
		&i.CreatedAtUnixMs,
		&i.UpdatedAtUnixMs,
	)
	return i, err
}

const listActiveTerminalSessionRoutes = `-- name: ListActiveTerminalSessionRoutes :many
SELECT
    scoped_session_id,
    node_id,
    lease_expires_unix_ms,
    last_used_unix_ms,
    created_at_unix_ms,
    updated_at_unix_ms
FROM terminal_session_routes
WHERE lease_expires_unix_ms > ?
ORDER BY node_id ASC, scoped_session_id ASC
`

func (q *Queries) ListActiveTerminalSessionRoutes(ctx context.Context, leaseExpiresUnixMs int64) ([]TerminalSessionRoute, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTerminalSessionRoutes, leaseExpiresUnixMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TerminalSessionRoute
	for rows.Next() {
		var i TerminalSessionRoute
		if err := rows.Scan(
			&i.ScopedSessionID,
			&i.NodeID,
			&i.LeaseExpiresUnixMs,
			&i.LastUsedUnixMs,
			&i.CreatedAtUnixMs,
			&i.UpdatedAtUnixMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTerminalSessionRoute = `-- name: UpsertTerminalSessionRoute :execrows
INSERT INTO terminal_session_routes (
    scoped_session_id,
    node_id,
    lease_expires_unix_ms,
    last_used_unix_ms,
    created_at_unix_ms,
    updated_at_unix_ms
) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(scoped_session_id) DO UPDATE SET
    lease_expires_unix_ms = MAX(terminal_session_routes.lease_expires_unix_ms, excluded.lease_expires_unix_ms),
    last_used_unix_ms = MAX(terminal_session_routes.last_used_unix_ms, excluded.last_used_unix_ms),
    updated_at_unix_ms = MAX(terminal_session_routes.updated_at_unix_ms, excluded.updated_at_unix_ms)
WHERE terminal_session_routes.node_id = excluded.node_id
`

type UpsertTerminalSessionRouteParams struct {
	ScopedSessionID    string `json:"scoped_session_id"`
	NodeID             string `json:"node_id"`
	LeaseExpiresUnixMs int64  `json:"lease_expires_unix_ms"`
	LastUsedUnixMs     int64  `json:"last_used_unix_ms"`
	CreatedAtUnixMs    int64  `json:"created_at_unix_ms"`
	UpdatedAtUnixMs    int64  `json:"updated_at_unix_ms"`
}

func (q *Queries) UpsertTerminalSessionRoute(ctx context.Context, arg UpsertTerminalSessionRouteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertTerminalSessionRoute,
		arg.ScopedSessionID,
		arg.NodeID,
		arg.LeaseExpiresUnixMs,
		arg.LastUsedUnixMs,
		arg.CreatedAtUnixMs,
		arg.UpdatedAtUnixMs,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
