server.port: ${SERVER_PORT:8080}

solon.app:
  name: 'onlyboxes'
  group: 'boxlite'

onlyboxes:
  lease:
    default-seconds: ${ONLYBOXES_DEFAULT_LEASE_SECONDS:30}

solon.logging:
  logger:
    "io.modelcontextprotocol.util.KeepAliveScheduler": ERROR
  appender:
    console:
      level: INFO
      pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %-19(%cyan(%-19.19logger{0})) : %msg%n"
    file:
      level: INFO
      pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-25level %-19(%-19.19logger{0}): %msg%n"
