services:
  console:
    image: coolfan1024/onlyboxes:{{IMAGE_TAG}}
    container_name: onlyboxes-console
    restart: unless-stopped
    environment:
      CONSOLE_HASH_KEY: "{{HASH_KEY}}"
      CONSOLE_ENABLE_REGISTRATION: "true"
      CONSOLE_DASHBOARD_USERNAME: "admin"     # only for first run
      CONSOLE_DASHBOARD_PASSWORD: "{{ADMIN_PASSWORD}}" # only for first run
      CONSOLE_INITIAL_ADMIN_API_KEY: "{{INITIAL_API_KEY}}" # explicit initial admin API key, only for first run
    ports:
      - "{{HTTP_PORT}}:8089"
      - "{{GRPC_PORT}}:50051"
    volumes:
      - ./db:/var/lib/onlyboxes/db
